MACRO
A1 &X, &Y, &R=AREG
MOVER &R, &X
ADD &R, &Y
MOVEM &R, &X
MEND
MACRO
INCR_M &MEM_VAL= &INCR_VAL= &REG=
MOVER &REG, &MEM_VAL
ADD &REG, &INCR_VAL
MOVEM &REG, &MEM_VAL
MEND
MACRO
INCR &MEM_VAL, &INCR_VAL, &REG
MOVER &REG, &MEM_VAL
ADD &REG, &INCR_VAL
MOVEM &REG, &MEM_VAL
MEND
START
A1 10, 20
INCR_M MEMVAL=A, INCR_VAL=B, REG=AREG
INCR A, B, AREG
END
