/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleDLL */

#ifndef _Included_SampleDLL
#define _Included_SampleDLL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleDLL
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SampleDLL_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
